#!/bin/bash
# oracle-memory.sh - Universal Oracle DB memory operations via SQLcl + Ollama
# Usage: ./oracle-memory.sh <action> [params...]

set -e

# ============================================================
# Configuration
# ============================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${ORACLE_MEMORY_CONFIG_DIR:-$HOME/.oracle-memory}"
CONFIG_FILE="$CONFIG_DIR/config.env"

# Defaults
ORACLE_HOST="${ORACLE_HOST:-localhost}"
ORACLE_PORT="${ORACLE_PORT:-1521}"
ORACLE_SERVICE="${ORACLE_SERVICE:-ORCL}"
ORACLE_USER="${ORACLE_USER:-}"
ORACLE_PASS="${ORACLE_PASS:-}"
SQLCL_PATH="${SQLCL_PATH:-sql}"
JAVA_HOME="${JAVA_HOME:-}"
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
EMBED_MODEL="${EMBED_MODEL:-bge-m3}"

# Load config file if exists
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
fi

export PATH="$JAVA_HOME/bin:$PATH" 2>/dev/null || true
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

TMP_DIR="/tmp/oracle-memory-$$"
mkdir -p "$TMP_DIR"
trap "rm -rf $TMP_DIR" EXIT

# ============================================================
# Helpers
# ============================================================
validate_config() {
    local missing=()
    [[ -z "$ORACLE_HOST" ]] && missing+=("ORACLE_HOST")
    [[ -z "$ORACLE_USER" ]] && missing+=("ORACLE_USER")
    [[ -z "$ORACLE_PASS" ]] && missing+=("ORACLE_PASS")
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        echo "❌ Missing configuration: ${missing[*]}"
        echo ""
        echo "Run: $0 setup"
        echo "Or set environment variables:"
        echo "  export ORACLE_HOST=<host> ORACLE_USER=<user> ORACLE_PASS=<pass>"
        return 1
    fi
    
    # Check SQLcl
    if ! command -v "$SQLCL_PATH" &>/dev/null; then
        echo "⚠️  SQLcl not found at: $SQLCL_PATH"
        echo "   Set SQLCL_PATH or install SQLcl"
        return 1
    fi
    return 0
}

run_sql_file() {
    local sql_file="$1"
    local conn="$ORACLE_USER/$ORACLE_PASS@//$ORACLE_HOST:$ORACLE_PORT/$ORACLE_SERVICE"
    "$SQLCL_PATH" -S "$conn" @"$sql_file" 2>/dev/null | grep -v "^WARNING" | grep -v "^$" | grep -v "^Bad\|More Details\|https://\|Error starting\|In command\|Error at\|SQL Error"
}

get_embedding() {
    local text="$1"
    local escaped_text
    escaped_text=$(python3 -c "import json,sys; print(json.dumps(sys.argv[1]))" "$text")
    local response
    response=$(curl -s --connect-timeout 10 "$OLLAMA_URL/api/embed" \
        -H "Content-Type: application/json" \
        -d "{\"model\":\"$EMBED_MODEL\",\"input\":$escaped_text}")
    echo "$response" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if 'embeddings' in data and len(data['embeddings']) > 0:
    vec = data['embeddings'][0]
    print('[' + ','.join(str(x) for x in vec) + ']')
else:
    print('ERROR: ' + json.dumps(data))
" 2>/dev/null
}

save_config() {
    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_FILE" << EOF
# Oracle Memory Configuration
# Generated by oracle-memory.sh setup
ORACLE_HOST="$ORACLE_HOST"
ORACLE_PORT="$ORACLE_PORT"
ORACLE_SERVICE="$ORACLE_SERVICE"
ORACLE_USER="$ORACLE_USER"
ORACLE_PASS="$ORACLE_PASS"
SQLCL_PATH="$SQLCL_PATH"
JAVA_HOME="$JAVA_HOME"
OLLAMA_URL="$OLLAMA_URL"
EMBED_MODEL="$EMBED_MODEL"
EOF
    chmod 600 "$CONFIG_FILE"
}

# ============================================================
# Actions
# ============================================================
action_setup() {
    echo "=== Oracle Memory Setup ==="
    echo ""
    echo "Configure your Oracle DB and embedding model."
    echo "Leave blank to use defaults."
    echo ""
    
    read -p "Oracle Host [$ORACLE_HOST]: " val; ORACLE_HOST="${val:-$ORACLE_HOST}"
    read -p "Oracle Port [$ORACLE_PORT]: " val; ORACLE_PORT="${val:-$ORACLE_PORT}"
    read -p "Oracle Service [$ORACLE_SERVICE]: " val; ORACLE_SERVICE="${val:-$ORACLE_SERVICE}"
    read -p "Oracle User: " val; [[ -n "$val" ]] && ORACLE_USER="$val"
    read -s -p "Oracle Password: " val; echo; [[ -n "$val" ]] && ORACLE_PASS="$val"
    read -p "SQLcl Path (or 'sql' if in PATH) [$SQLCL_PATH]: " val; SQLCL_PATH="${val:-$SQLCL_PATH}"
    read -p "JAVA_HOME (optional): " val; [[ -n "$val" ]] && JAVA_HOME="$val"
    read -p "Ollama URL [$OLLAMA_URL]: " val; OLLAMA_URL="${val:-$OLLAMA_URL}"
    read -p "Embedding Model [$EMBED_MODEL]: " val; EMBED_MODEL="${val:-$EMBED_MODEL}"
    echo ""
    
    save_config
    echo "✅ Configuration saved to: $CONFIG_FILE"
    echo ""
    
    # Test connection
    echo "Testing connection..."
    if action_status 2>/dev/null | grep -q "Connected"; then
        echo "✅ Connection successful!"
    else
        echo "⚠️  Connection test failed. Check your settings."
    fi
}

action_status() {
    if ! validate_config; then return 1; fi
    
    echo "=== Oracle Memory Status ==="
    echo ""
    echo "Config: $CONFIG_FILE"
    echo "DB: $ORACLE_HOST:$ORACLE_PORT/$ORACLE_SERVICE ($ORACLE_USER)"
    echo "Ollama: $OLLAMA_URL ($EMBED_MODEL)"
    echo ""
    
    # Check DB
    echo "SELECT 'OK' FROM dual;" > "$TMP_DIR/check.sql"
    local db_check
    db_check=$(run_sql_file "$TMP_DIR/check.sql" 2>/dev/null)
    if [[ "$db_check" == *"OK"* ]]; then
        echo "✅ Database: Connected"
    else
        echo "❌ Database: Connection failed"
        return 1
    fi
    
    # Check Ollama
    local ollama_check
    ollama_check=$(curl -s --connect-timeout 5 "$OLLAMA_URL/api/tags" | python3 -c "import sys,json; d=json.load(sys.stdin); print('OK' if any('$EMBED_MODEL' in m.get('name','') for m in d.get('models',[])) else 'MISSING')" 2>/dev/null)
    if [[ "$ollama_check" == "OK" ]]; then
        echo "✅ Ollama: $EMBED_MODEL available"
    else
        echo "⚠️  Ollama: $EMBED_MODEL not found"
    fi
    
    # Check tables
    echo ""
    echo "=== Tables ==="
    echo "SELECT table_name FROM user_tables WHERE table_name IN ('MEM_VECTORS','GRAPH_CONCEPTS','GRAPH_RELATIONS') ORDER BY table_name;" > "$TMP_DIR/tables.sql"
    run_sql_file "$TMP_DIR/tables.sql" 2>/dev/null | while read line; do
        echo "SELECT COUNT(*) FROM $line;" > "$TMP_DIR/cnt.sql"
        local count
        count=$(run_sql_file "$TMP_DIR/cnt.sql" 2>/dev/null | grep -oE '[0-9]+')
        echo "  📋 $line ($count rows)"
    done
}

action_search() {
    local query="$1"
    local top_k="${2:-5}"
    if [[ -z "$query" ]]; then
        echo "Usage: $0 search <query> [top_k]"
        return 1
    fi
    if ! validate_config; then return 1; fi
    
    local vec_str
    vec_str=$(get_embedding "$query")
    if [[ "$vec_str" == ERROR* ]]; then
        echo "❌ Embedding failed: $vec_str"
        return 1
    fi
    
    echo "=== Search: '$query' (top $top_k) ==="
    
    python3 - "$vec_str" "$top_k" "$TMP_DIR/search.sql" << 'PYEOF'
import sys
vec_str, top_k, sql_file = sys.argv[1], sys.argv[2], sys.argv[3]
sql = f"""SET SERVEROUTPUT ON SIZE 1000000
DECLARE
  l_result CLOB;
BEGIN
  l_result := DBMS_VECTOR_DATABASE.SEARCH(
    table_name => 'MEM_VECTORS',
    query_by   => JSON('{{"vector":{vec_str}}}'),
    top_k      => {top_k}
  );
  DBMS_OUTPUT.PUT_LINE(l_result);
END;
/
"""
with open(sql_file, 'w') as f:
    f.write(sql)
PYEOF
    
    run_sql_file "$TMP_DIR/search.sql" 2>/dev/null | python3 -c "
import sys, json
for line in sys.stdin:
    line = line.strip()
    if line.startswith('{'):
        try:
            data = json.loads(line)
            results = data.get('results', [])
            if results:
                for i, r in enumerate(results, 1):
                    meta = r.get('metadata', {})
                    text = meta.get('text', 'N/A')
                    dist = r.get('distance', 0)
                    sim = round(1 - dist, 4)
                    cat = meta.get('category', '')
                    tags = meta.get('tags', '')
                    print(f'  [{sim}] {text}')
                    parts = []
                    if cat: parts.append(f'[{cat}]')
                    if tags: parts.append(tags)
                    if parts: print('       ' + ' | '.join(parts))
            else:
                print('  No results found.')
        except:
            pass
" 2>/dev/null
}

action_write() {
    local text="$1"
    local category="${2:-}"
    local tags="${3:-}"
    if [[ -z "$text" ]]; then
        echo "Usage: $0 write <text> [category] [tags]"
        return 1
    fi
    if ! validate_config; then return 1; fi
    
    local vec_str
    vec_str=$(get_embedding "$text")
    if [[ "$vec_str" == ERROR* ]]; then
        echo "❌ Embedding failed: $vec_str"
        return 1
    fi
    
    python3 - "$text" "$category" "$tags" "$vec_str" "$TMP_DIR/write.sql" << 'PYEOF'
import json, sys
text = sys.argv[1]
category = sys.argv[2] if len(sys.argv) > 2 else ''
tags = sys.argv[3] if len(sys.argv) > 3 else ''
vec = sys.argv[4]
sql_file = sys.argv[5]

meta = {'text': text}
if category: meta['category'] = category
if tags: meta['tags'] = tags
meta_json = json.dumps(meta, ensure_ascii=False)

meta_escaped = meta_json.replace("'", "''")
vec_escaped = vec.replace("'", "''")

sql = f"""SET SERVEROUTPUT ON
DECLARE
  l_vec VARCHAR2(32767) := '{vec_escaped}';
  l_meta VARCHAR2(32767) := '{meta_escaped}';
BEGIN
  EXECUTE IMMEDIATE
    'INSERT INTO mem_vectors (dense_vector, metadata) VALUES (VECTOR(:1), JSON(:2))'
    USING l_vec, l_meta;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Written');
END;
/
"""
with open(sql_file, 'w', encoding='utf-8') as f:
    f.write(sql)
PYEOF
    
    run_sql_file "$TMP_DIR/write.sql" 2>/dev/null
}

action_list() {
    local limit="${1:-10}"
    if ! validate_config; then return 1; fi
    
    echo "=== Memory List (limit: $limit) ==="
    
    cat > "$TMP_DIR/list.sql" << EOF
SELECT JSON_VALUE(metadata, '\$.text') AS text,
       JSON_VALUE(metadata, '\$.category') AS category,
       JSON_VALUE(metadata, '\$.tags') AS tags
FROM mem_vectors
WHERE ROWNUM <= $limit
ORDER BY ID;
EOF
    
    run_sql_file "$TMP_DIR/list.sql" 2>/dev/null
}

action_delete() {
    local text="$1"
    if [[ -z "$text" ]]; then
        echo "Usage: $0 delete <text_match>"
        return 1
    fi
    if ! validate_config; then return 1; fi
    
    cat > "$TMP_DIR/delete.sql" << EOF
SET SERVEROUTPUT ON
DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM mem_vectors
  WHERE JSON_VALUE(metadata, '\$.text') LIKE '%$text%';
  IF l_count > 0 THEN
    DELETE FROM mem_vectors WHERE JSON_VALUE(metadata, '\$.text') LIKE '%$text%';
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Deleted ' || l_count || ' record(s)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('No matching records found');
  END IF;
END;
/
EOF
    
    run_sql_file "$TMP_DIR/delete.sql" 2>/dev/null
}

action_graph() {
    local concept="$1"
    local depth="${2:-2}"
    if [[ -z "$concept" ]]; then
        echo "Usage: $0 graph <concept_name> [depth]"
        return 1
    fi
    if ! validate_config; then return 1; fi
    
    echo "=== Graph Search: '$concept' (depth: $depth) ==="
    
    cat > "$TMP_DIR/graph.sql" << EOF
WITH paths (src, dst, chain, depth) AS (
  SELECT c1.name, c2.name, r.relation_type, 1
  FROM graph_relations r
  JOIN graph_concepts c1 ON r.src_concept_id = c1.concept_id
  JOIN graph_concepts c2 ON r.dst_concept_id = c2.concept_id
  WHERE c1.name LIKE '%$concept%'
  UNION ALL
  SELECT p.src, c2.name, p.chain || ' -> ' || r.relation_type, p.depth + 1
  FROM paths p
  JOIN graph_relations r ON r.src_concept_id = (
    SELECT concept_id FROM graph_concepts WHERE name = p.dst
  )
  JOIN graph_concepts c2 ON r.dst_concept_id = c2.concept_id
  WHERE p.depth < $depth
)
CYCLE dst SET is_cycle TO 'Y' DEFAULT 'N'
SELECT src, dst, chain, depth FROM paths WHERE is_cycle = 'N' ORDER BY depth, dst;
EOF
    
    run_sql_file "$TMP_DIR/graph.sql" 2>/dev/null
}

action_init() {
    echo "=== Initialize Oracle Memory Tables ==="
    if ! validate_config; then return 1; fi
    
    cat > "$TMP_DIR/init.sql" << 'SQLEOF'
-- Create vector table
DECLARE
  l_result CLOB;
BEGIN
  BEGIN
    l_result := DBMS_VECTOR_DATABASE.CREATE_VECTOR_TABLE(
      table_name       => 'MEM_VECTORS',
      description      => 'Agent memory vectors',
      auto_generate_id => TRUE,
      vector_type      => 'dense'
    );
    DBMS_OUTPUT.PUT_LINE('✅ Created MEM_VECTORS');
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        DBMS_OUTPUT.PUT_LINE('⚠️  MEM_VECTORS already exists');
      ELSE
        RAISE;
      END IF;
  END;
END;
/

-- Create graph tables
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE graph_concepts (
    concept_id VARCHAR2(40) PRIMARY KEY,
    name VARCHAR2(500),
    category VARCHAR2(100),
    description VARCHAR2(4000)
  )';
  DBMS_OUTPUT.PUT_LINE('✅ Created GRAPH_CONCEPTS');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    DBMS_OUTPUT.PUT_LINE('⚠️  GRAPH_CONCEPTS already exists');
  ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE graph_relations (
    relation_id NUMBER GENERATED ALWAYS AS IDENTITY,
    src_concept_id VARCHAR2(40),
    dst_concept_id VARCHAR2(40),
    relation_type VARCHAR2(100),
    weight NUMBER DEFAULT 1.0,
    CONSTRAINT fk_src FOREIGN KEY (src_concept_id) REFERENCES graph_concepts(concept_id),
    CONSTRAINT fk_dst FOREIGN KEY (dst_concept_id) REFERENCES graph_concepts(concept_id)
  )';
  DBMS_OUTPUT.PUT_LINE('✅ Created GRAPH_RELATIONS');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN
    DBMS_OUTPUT.PUT_LINE('⚠️  GRAPH_RELATIONS already exists');
  ELSE RAISE; END IF;
END;
/

-- Create property graph
BEGIN
  EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH memory_graph';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE PROPERTY GRAPH memory_graph
    VERTEX TABLES (graph_concepts KEY (concept_id) PROPERTIES (name, category, description))
    EDGE TABLES (graph_relations KEY (relation_id)
      SOURCE KEY (src_concept_id) REFERENCES graph_concepts(concept_id)
      DESTINATION KEY (dst_concept_id) REFERENCES graph_concepts(concept_id)
      PROPERTIES (relation_type, weight) LABEL relation_type)';
  DBMS_OUTPUT.PUT_LINE('✅ Created MEMORY_GRAPH');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('⚠️  CREATE PROPERTY GRAPH: ' || SQLERRM);
END;
/
SQLEOF
    
    run_sql_file "$TMP_DIR/init.sql" 2>/dev/null
}

# ============================================================
# Main
# ============================================================
case "${1:-}" in
    setup)   action_setup ;;
    init)    action_init ;;
    status)  action_status ;;
    search)  action_search "$2" "$3" ;;
    write)   action_write "$2" "$3" "$4" ;;
    list)    action_list "$2" "$3" ;;
    delete)  action_delete "$2" ;;
    graph)   action_graph "$2" "$3" ;;
    *)
        echo "Oracle Memory Tool - Universal Semantic Memory for Oracle AI Database"
        echo ""
        echo "Usage: $0 <action> [params...]"
        echo ""
        echo "Actions:"
        echo "  setup                         - Interactive configuration"
        echo "  init                          - Create required tables"
        echo "  status                        - Check connection and tables"
        echo "  search <query> [top_k]        - Semantic search"
        echo "  write <text> [cat] [tags]     - Write memory"
        echo "  list [limit]                  - List memories"
        echo "  delete <text_match>           - Delete by text"
        echo "  graph <concept> [depth]       - Graph relationship query"
        echo ""
        echo "Configuration (env vars or ~/.oracle-memory/config.env):"
        echo "  ORACLE_HOST, ORACLE_PORT, ORACLE_SERVICE"
        echo "  ORACLE_USER, ORACLE_PASS"
        echo "  SQLCL_PATH (default: sql)"
        echo "  JAVA_HOME, OLLAMA_URL, EMBED_MODEL"
        ;;
esac
