#!/usr/bin/env python3
"""
generate_vector_insert_sql.py - Generate SQL INSERT statements for Oracle AI Database vector import (v0.3.1)

Usage:
    python generate_vector_insert_sql.py "Your text content" --node-id 9996 --node-type "test_type"

Output:
    Generates a complete PL/SQL block with CLOB + TO_VECTOR() method for vector insertion.
"""

import json
import argparse
import sys
import urllib.request

# Configuration
LM_STUDIO_URL = "http://10.10.10.1:12345/v1/embeddings"
DEFAULT_MODEL = "text-embedding-bge-m3"


def get_embedding(text: str, model: str = DEFAULT_MODEL) -> dict:
    """Get vector embedding from LM Studio API."""
    
    payload = json.dumps({
        "model": model,
        "input": text
    }).encode('utf-8')
    
    req = urllib.request.Request(
        LM_STUDIO_URL,
        data=payload,
        headers={'Content-Type': 'application/json'},
        method='POST'
    )
    
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode('utf-8'))
            
            if "data" in result and len(result["data"]) > 0:
                return {
                    "embedding": result["data"][0]["embedding"],
                    "model": model,
                    "success": True
                }
            else:
                raise Exception("Unexpected API response format")
                
    except Exception as e:
        print(f"Error getting embedding: {e}", file=sys.stderr)
        sys.exit(1)


def generate_sql(node_id: int, node_type: str, embedding: list, metadata: dict = None) -> str:
    """Generate PL/SQL INSERT statement with CLOB + TO_VECTOR() method."""
    
    # Convert embedding to JSON string (CLOB content)
    vec_string = json.dumps(embedding)
    
    # Prepare metadata JSON
    if metadata is None:
        metadata = {
            "import_method": "CLOB_TO_VECTOR_v0.3.1",
            "vector_dimensions": len(embedding),
            "timestamp": "SYSTIMESTAMP"
        }
    else:
        metadata["import_method"] = "CLOB_TO_VECTOR_v0.3.1"
        metadata["vector_dimensions"] = len(embedding)
    
    # Generate SQL
    sql = f"""-- Generated by generate_vector_insert_sql.py (v0.3.1)
-- Method: CLOB + TO_VECTOR() for Oracle AI Database 26ai

DECLARE
    l_embedding CLOB;  -- ⭐ CLOB type supports long vector strings (~{len(vec_string)} chars)
BEGIN
    l_embedding := '{vec_string}';
    
    EXECUTE IMMEDIATE 
        'INSERT INTO openclaw.memory_nodes (node_id, node_type, embedding) VALUES (:1, :2, TO_VECTOR(:3))'
        USING {node_id}, '{node_type}', l_embedding;
    
    COMMIT;
END;
/

-- Verify insertion
SELECT 
    node_id, 
    node_type,
    vector_dimension_count(embedding) as dimensions,
    CASE WHEN vector_dimension_count(embedding) = 1024 THEN '✅ SUCCESS' ELSE '❌ FAILED' END as status
FROM openclaw.memory_nodes
WHERE node_id = {node_id};
"""
    
    return sql


def main():
    parser = argparse.ArgumentParser(
        description="Generate SQL INSERT statement for Oracle AI Database vector import"
    )
    parser.add_argument("text", help="Text content to generate embedding for")
    parser.add_argument("--node-id", type=int, default=9996, help="Node ID (default: 9996)")
    parser.add_argument("--node-type", type=str, default="auto_generated", help="Node type (default: auto_generated)")
    parser.add_argument("--output", type=str, help="Output SQL file (default: stdout)")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help=f"Embedding model (default: {DEFAULT_MODEL})")
    
    args = parser.parse_args()
    
    # Get embedding from API
    print(f"Getting embedding for text: '{args.text[:50]}...'")
    result = get_embedding(args.text, args.model)
    
    if not result["success"]:
        sys.exit(1)
    
    print(f"✓ Embedding generated successfully ({len(result['embedding'])} dimensions)")
    
    # Generate SQL
    sql = generate_sql(args.node_id, args.node_type, result["embedding"])
    
    # Output
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(sql)
        print(f"✓ SQL saved to {args.output}")
    else:
        print("\n--- Generated SQL ---\n")
        print(sql)


if __name__ == "__main__":
    main()
